### ISSUE TITLE
Plugin will work if i click the video before

### ISSUE THREAD

**Issue by kipotlea** [ctd1500/videojs-hotkeys#10]
Plugin will work if i click the video before. how to resolve it?

**Comment by ctd1500** [comment]
I'm not sure I understand, do you mean it will only work if you click the video first? 

If so, the video player requires focus (clicking) in order to use hotkeys. 
This is the same case for other video players such as Youtube.

**Comment by kipotlea** [comment]
yes. it will work if i click the vide first?  you have solution for this? because hotkey from video  vid.me  work without click the video first. you can check this : https://vid.me/WaJr

**Comment by ctd1500** [comment]
That site is probably using something similar to:
```js
videojs('video-player').ready(function() {
    this.el().focus();
});
```
Which focuses the video player upon load.

If you don't auto-play the video, you could also do something like this upon clicking the poster/play button to force focus:
```js
videojs('video-player').ready(function() {
    videojs('video-player').on('play', function() {
        this.el().focus();
    });
});
```

**Comment by kipotlea** [comment]
Thank you so much.. it works... :)

**Comment by kipotlea** [comment]
this hotkey not work if the video fullscreen. right?

**Comment by ctd1500** [comment]
Yes, It should work while fullscreen.  It works fine in fullscreen in all my tests.
