### ISSUE TITLE
Hotkeys disabled when control buttons focused

### ISSUE THREAD

**Issue by nhardy** [ctd1500/videojs-hotkeys#16]
@ctd1500

This particular line disables hotkeys: https://github.com/ctd1500/videojs-hotkeys/blob/master/videojs.hotkeys.js#L71

The comment above this section suggests an option to disable this behaviour, but there is no option available.
The comment suggests disabling is possible if in jogStyle mode, but this does not seem like the correct name for such a control. Perhaps a new option is required?

One particular example:
User clicks fullscreen button, then presses spacebar to pause.

Expected behaviour:
Video goes fullscreen, then is paused.

Actual behaviour:
Video goes fullscreen, then exits fullscreen.

I am able to submit a PR which fixes the issue if required.

**Comment by ctd1500** [comment]
It acts this way so as to not override accessibility options (tabbing between buttons, and hitting space to "click" them).
But if you'd like, you can submit a PR to add an option to disable that.

**Comment by nhardy** [comment]
In #18 I've made the option default to false, but I would argue that because `ENTER`/`RETURN` can be used instead of `SPACE` for accessibility, that the option should perhaps default to `true` from 0.3 onward.
