### ISSUE TITLE
Refactor KeyCombination [enhancement]

### ISSUE THREAD

**Issue by ReNDeZOwnler** [ctd1500/videojs-hotkeys#20]
Hi,

I have made a complete refactor of the plugin. I have to be able to add new shortcuts in the plugin and some of them have a key combination like ctrl + enter, ctrl + D,...

You can checkout at
https://github.com/ReNDeZOwnler/videojs-hotkeys/blob/keyCombination/videojs.hotkeys.js

Give me your feedback pls

**Comment by ctd1500** [comment]
I took a look, but it seemed to require editing the plugin itself in order to specify any sort of customized keys.

Perhaps you need other custom keys that I haven't built yet, but maybe this format can work better?
https://github.com/ctd1500/videojs-hotkeys/blob/modular/videojs.hotkeys.js

This would allow for easily replacing hotkeys with your own with an option parameter, without requiring editing the plugin script.
For example, replacing / changing the fullscreen hotkey:
```js
this.hotkeys({
  volumeStep: 0.2,
  enableFullscreen: true,
  fullscreenKey: function(e) {
    // fullscreen with the F key or Ctrl+Enter
    return ((e.which === 70) || (e.ctrlKey && e.which === 13));
  }
});
```

**Comment by ReNDeZOwnler** [comment]
Ok, I give it a try.

In my case I need to provide hotkeys to:
** Add new simple hotkey **
* Toggle subtitules with S Key

** Enhance existing simple hotkey with a complex hotkey **
* Toggle FullScreen with CTRL + ENTER

** Add new complex hotkey **
* Toggle "awesome behaviour " with CTRL + D

I will rewrite my code following your way.

**Comment by ctd1500** [comment]
I can change this a little bit, to enable such functionality.

**Comment by ctd1500** [comment]
I've just updated the branch.
https://github.com/ctd1500/videojs-hotkeys/blob/modular/videojs.hotkeys.js

Something simple like this could be done.

```js
this.hotkeys({
  playPauseKey: function(e, player) {
    // spacebar toggle Play/Pause
    if (e.which === 32) {
      return true;
    }

    // catch "S" key for subtitles
    if (e.which === 83) {
      // Toggle subtitles with code here, or call another function you wrote
      toggleSubtitles();
      // return false so that we don't play/pause when toggling subtitles.
      return false;
    }
    return false;
  }
});
```
Or I could also add a `customKey: function(e, player) { }` function to add any new keys without overriding existing keys.

```js
this.hotkeys({
  customKey: function(e, player) {
    // catch "S" key for subtitles
    if (e.which === 83) {
      // Toggle subtitles with code here, or call another function you wrote
      toggleSubtitles();
    }
    // Wouldn't need to return anything, since the customKey function would 
    // not do anything by itself.
    return;
  }
});
```

**Comment by ReNDeZOwnler** [comment]
Hi,

Checkout my branch:
https://github.com/ReNDeZOwnler/videojs-hotkeys/tree/modular

* videojs.hotkeys.js
* example.html

**Comment by ctd1500** [comment]
I just gave it a test run, it seems pretty good to me.
Want to create a pull request?  Then I can start putting it into the next release.

**Comment by ReNDeZOwnler** [comment]
Ok, I have some other suggestions.

I'll create a pull request for this a threat the other things in other issues.

**Comment by ReNDeZOwnler** [comment]
You can close issue this when you merge the pull request.

**Comment by ctd1500** [comment]
Thanks.
