### ISSUE TITLE
UMD version

### ISSUE THREAD

**Issue by ReNDeZOwnler** [ctd1500/videojs-hotkeys#23]
Hi,

I use your plugin inside a require.js module application so I need to "requirerize" the plugin.
I think will be good to UMD this plugin. UMD: http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

You can easily solve this problema wraping your code in:

    ;(function (root, factory) {
      if (typeof define === 'function' && define.amd) {
        define([], factory.bind(this, root));
      } else if(typeof module !== 'undefined' && module.exports) {
        module.exports = factory(root);
      } else {
        root.videojsMediaSources = factory(root);
      }
    
    //Plugin starts here
    (function(window, videojs) {
       'use strict';
       window['videojs_hotkeys'] = { version: "0.2.8" };

    ....

    // Plugin ends
      videojs.plugin('hotkeys', hotkeys);
    })(window, window.videojs);

    
    });

In UMD we can use the plugin as always plus AMD, CommonJS, and UMD.

Regards

**Comment by ctd1500** [comment]
What I've written seems to work for me, but I don't actually use require.js, or any of those module systems for browser code.

https://github.com/ctd1500/videojs-hotkeys/blob/modular/videojs.hotkeys.js
So if you could give this a try and see if you have any issues in how you use it, that would be helpful.

**Comment by ReNDeZOwnler** [comment]
wow, looks pretty good.

I'll test it later.

**Comment by ReNDeZOwnler** [comment]
It's better to let the name empty, so the name of the module will be the plugin file (you can control the name that do you want). Require Optimization (http://requirejs.org/docs/optimization.html)

More info at http://requirejs.org/docs/api.html#modulename
> You can explicitly name modules yourself, but it makes the modules less portable
> if you move the file to another directory you will need to change the name.



I think we have to suppose that the developer has pre-load VideoJS before. I have tryied the following code and I think it has to be like this.

    if (typeof define === 'function' && define.amd) {
      define([], factory.bind(this, root, root.videojs));
    } else if (typeof module !== 'undefined' && module.exports) {
      module.exports = factory(root, root.videojs);
    } else {
      root['videojs.hotkeys'] = factory(root, root.videojs);
    }

Regards

**Comment by ctd1500** [comment]
Alright, I've updated the branch to reflect that.

Except for this part:
```js
root['videojs.hotkeys'] = factory(root, root.videojs);
```
As there's nothing that needs to be returned, and trying to set that global variable could have a negative side effect on the version object below that.

**Comment by ReNDeZOwnler** [comment]
oh ok. Then only let:

    factory(root, root.videojs);

**Comment by ReNDeZOwnler** [comment]
Tried successfully on my require.js project.
