### ISSUE TITLE
Any reason why `const` is the only es6 feature used?

### ISSUE THREAD

**Issue by chemoish** [ctd1500/videojs-hotkeys#24]
https://github.com/ctd1500/videojs-hotkeys/blob/master/videojs.hotkeys.js#L43

Obviously this breaks anything that doesn't support it.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

**Comment by ctd1500** [comment]
Good question.  I've been writing in other languages a lot recently, I probably wrote it out of habit and it worked in my tests so it stuck.  I'll change it over to a var.

**Comment by chemoish** [comment]
You can always use babel if you want to go full bleeds.

I am using:

```js
import 'babel-loader!imports-loader?this=>window,define=>false!videojs-hotkeys';
```

In the mean time.

**Comment by chemoish** [comment]
Ty.
