### ISSUE TITLE
focus return after submenu (playbackRates/resolutions)

### ISSUE THREAD

**Issue by H1D** [ctd1500/videojs-hotkeys#30]
Hi! There is a problem with returning focus after changing something using control-bar submenu. I have a few thoughts on hot to fix this, but I decided to discuss first.

**Problem**
Plugin trying to return focus to `<video>` after user interaction with control-bar. This done by determining either active element is inside control-bar or not. Problem that after clicking any submenu focus obviously goes to that submenu. Then when menu fades away videojs wipes it out of DOM and focus goes to `<body>` so plugin has no chance to determine later did user interacted with control-bar or not. Focus stays at `<body>` and hotkeys doesn't work =(

**Solution 1 (wrong)**
Turn on `alwaysCaptureHotkeys` and give up accessibility

**Solution 2 (ugly & non reliable)**
add something like this to return focus manually:
```
player.on 'ratechange', => player.el().focus()
player.on 'resolutionchange', => player.el().focus()
```
But `resolutionchange` here is a custom event came from resolution change plugin. Who knows how many plugins can be used

**Solution 3**
???

**Comment by ctd1500** [comment]
It's a rather difficult issue since there are so many variables in play from added button plugins.
I'm unsure of any truly good solution.

**Comment by H1D** [comment]
Maybe we can PR `videojs` itself. For example add `user_intercation_end` event.

BTW almost all plugins use videojs standart classes to create menus and buttons – https://github.com/videojs/video.js/tree/master/src/js/menu

**Comment by ctd1500** [comment]
If you can come up with an event they will accept into the video.js core, then I will certainly add support  for it to the plugin afterwards.
