### ISSUE TITLE
Hi!,Need help

### ISSUE THREAD

**Issue by sky-beyond** [ctd1500/videojs-hotkeys#32]
Hi!, Need help for  implement your plugin with videojs  4.12

Demo:

http://xaphanentertainment.com/pop-in/player-test/

not working with key board shortcuts.. can anyone looked and tell me whats wrong? in my code

Kindly regards!,
Sam

**Comment by ctd1500** [comment]
The hotkeys are working for me, but you do have to click on the video to get them to work.

Also, you have a lot of the extra code from the example.html in your source which will cause warnings.

This is the minimum you need for the plugin to work:
```js
videojs('video').ready(function() {
  this.hotkeys({
    volumeStep: 0.1,
    seekStep: 5
  });
});
```
The rest are optional and don't need to be included unless you want to change them.
