### ISSUE TITLE
Reduce or increase the size of the subtitles

### ISSUE THREAD

**Issue by surikat1978** [ctd1500/videojs-hotkeys#34]
Thank you again for the plug! Is it possible to reduce or increase the size of the subtitles using the keys - +
on keyboard?
It would be a very useful option ..!

**Comment by aitoraznar** [comment]
You can do it yourself with Custom Hotkeys.
Explained in this section https://github.com/ctd1500/videojs-hotkeys#custom-hotkeys-and-overrides

**Comment by surikat1978** [comment]
Unfortunately there is nothing said about  using the keys  - + for  increase , decrease, captions ?
it was very useful to do by default !

**Comment by aitoraznar** [comment]
@surikat1978 
I suggested the use of Custom keys to create your own shortkey.
I made a basic example (of increase font size) to illustrate you, I haven't tried, it's only to guide you.

`videojs('vidId').ready(function() {
  this.hotkeys({
    volumeStep: 0.1,
    customKeys: {
      // Create custom hotkeys
      increaseCaptionSize: {
        key: function(event) {
          //107: Plus key
          //171: Numeric plus key
          return (event.which === 107 || event.which === 171);
        },
        handler: function(player, options, event) {
          //player.muted(!player.muted());

          //Here increase the size using CSS classes, directly in a style tag... it is up to you
          videojs('veoplayer_html5_api').textTrackDisplay.el().style['font-size'] = '50px'
        }
      }
    }
  });
});
`

**Comment by surikat1978** [comment]
I have a plugin initialization file  libs.js  in my template:

$(document).ready(function() {
	videojs('2sub').ready(function() {
            this.hotkeys({
			volumeStep: 0.1,
			seekStep: 5,
			enableMute: true,
			enableVolumeScroll: true,
			enableFullscreen: true,
			enableNumbers: true,
			
		});  
	});


});

added this kind of 

$(document).ready(function() {
	videojs('testvideo').ready(function() {
            this.hotkeys({
			volumeStep: 0.1,
			seekStep: 5,
			enableMute: true,
			enableVolumeScroll: true,
			enableFullscreen: true,
			enableNumbers: true,
			customKeys: {
      // Create custom hotkeys
      increaseCaptionSize: {
        key: function(event) {
          //107: Plus key
          //171: Numeric plus key
          return (event.which === 107 || event.which === 171);
        },
        handler: function(player, options, event) {
          //player.muted(!player.muted());
          //Here increase the size using CSS classes, directly in a style tag... it is up to you
          videojs('veoplayer_html5_api').textTrackDisplay.el().style['font-size'] = '50px'
        }
      }
    }
  });
});

And stopped showing subtitles and control of player ?!  
Maybe  need to add something to the videojs.hotkeys.min.js ?  Version  2.0.18

Thanks Very Much !
