### ISSUE TITLE
Page scroll on focus issue

### ISSUE THREAD

**Issue by ardaogulcan** [ctd1500/videojs-hotkeys#39]
When video paused and page is scrolled where the player is not visible, code for setting focus to the controlbar in userinactive event cause page to scroll up to the video again.

**Comment by burakkirkil** [comment]
Exactly what i need.

**Comment by efflux** [comment]
Is there a way to disable scroll/focus on the player? It seems like every interaction with the control bar is making the window jump a bit after a couple seconds.

**Comment by ctd1500** [comment]
@efflux Yes, setting `enableInactiveFocus: false` in the [options object](https://github.com/ctd1500/videojs-hotkeys/blob/master/README.md#enable-the-plugin) should do it.

**Comment by efflux** [comment]
@ctd1500 You rock, thanks! I remember looking at that when I added the plugin, but didn't put 2 and 2 together. Durrrr..

Thanks again.
