### ISSUE TITLE
videojs cant't  catch ended event when player seek forward until ending

### ISSUE THREAD

**Issue by SzHeJason** [ctd1500/videojs-hotkeys#42]

**Comment by swierczek** [comment]
I'll try to implement a PR for this, but a solution I got working is below:

    var seekStep = 5; //how many seconds to seek with arrow keys
    player.hotkeys({
	    seekStep: 0, //manually handle this below
	    rewindKey: function(event, player) {
		    event.preventDefault();
    
		    var time = player.currentTime();
		    if (event.which == 37) { //left arrow
			    player.currentTime(time-seekStep);
		    }
		    return false;
	    },
	    forwardKey: function(event, player) {
		    event.preventDefault();
    
		    var time = player.currentTime();
		    if (event.which == 39 && time+seekStep <= duration) { //right arrow
			    player.currentTime(time+seekStep);
		    } else if (event.which == 39) {
			    player.currentTime(duration);
		    }
		    return false;
	    }
    });
