### ISSUE TITLE
Plugin is using deprecated register function

### ISSUE THREAD

**Issue by MekliCZ** [ctd1500/videojs-hotkeys#47]
videojs-hotkeys is using videojs.plugin() instead of videojs.registerPlugin(). plugin() is deprecated and may be removed in future versions of videojs, so it would be nice to rewrite it to registerPlugin().

**Comment by borzaka** [comment]
Or make it future-proof:

```js
// Cross-compatibility for Video.js 5 and 6.
var registerPlugin = videojs.registerPlugin || videojs.plugin;
```
