### ISSUE TITLE
default page scroll not working 

### ISSUE THREAD

**Issue by sjayanths** [ctd1500/videojs-hotkeys#52]
Hi,

i enabled hotkeys plugin with 
```
this.hotkeys({
          volumeStep: 0.1,
          seekStep: 5,
          enableModifiersForNumbers: false,
          alwaysCaptureHotkeys: true

        });
```

When i scroll mouse wheel on the video, before clicking on the play icon, page scroll should work.
But seems the page is there in the same place. 
When I removed the hotkeys, page scroll working fine on the video.

**Comment by ctd1500** [comment]
`alwaysCaptureHotkeys: true` is the problem. 
That causes the VolumeScroll to override page scrolling, even if you haven't clicked on the video. 
That is why `alwaysCaptureHotkeys` is disabled by default, it alters accessibility and does things unexpected by most users.

**Comment by sjayanths** [comment]
Hi,
I created a plunker where i removed alwaysCaptureHotkeys, but i still face the issue.
The below link reproduces the issue i was raised.
http://plnkr.co/edit/c7tBtUDUzR15u2GiNZ8o?p=info

**Comment by ctd1500** [comment]
I've found I can only replicate this issue with chrome due to the way chrome handles scroll wheel events.
I'll release a fix that makes it consistent with other browsers.

**Comment by sjayanths** [comment]
Thank you very much.

**Comment by sjayanths** [comment]
I tested, 0.2.21 in chrome and safari.
In chrome it is working fine but in safari i can still see the issue.

**Comment by ctd1500** [comment]
I don't have safari, but I tried it in browserstack, they only offer safari 7.1 free, but it seemed to work on your plunker page.
Did you test using the cdn? It may have still been caching the old version.

**Comment by sjayanths** [comment]
Sorry, my bad. It was cached. It is working fine.
Thanks for quick fix.
