### ISSUE TITLE
Not working in new Chrome 69

### ISSUE THREAD

**Issue by Vitassam** [ctd1500/videojs-hotkeys#59]
As I can test, plugin didn't work in new version of Chrome (69) on MacOS Mojave.
It is strange, but in "private tab" of MacOS Chrome it (plugin) works.
But, as I suppose, plugin didn't work on Windows in Chrome (I received a letter from a user and I believe he uses Windows).

In new Safari 12 it works.

Personally I tested on Windows 10 in Chrome, and for me plugin works.

**Comment by frontHu** [comment]
how to resolved? i have the save problem

**Comment by ctd1500** [comment]
@frontHu I've tested in chrome/firefox/safari on Mac with browserstack and everything works fine at this time.  Is your comment here related to #63?  That appears to be a node issue, not a browser issue.
