### ISSUE TITLE
Can't resolve 'videojs' in '0.2.25@videojs-hotkeys'

### ISSUE THREAD

**Issue by frontHu** [ctd1500/videojs-hotkeys#63]
Can't resolve 'videojs' in '0.2.25@videojs-hotkeys'
引入import videojsHotkeys from 'videojs-hotkeys'.
 
![image](https://user-images.githubusercontent.com/19454392/52832708-ad69a680-3114-11e9-9f7d-a728e8377279.png)

**Comment by ctd1500** [comment]
I can't offer much help with using this as a node import, but the important code would be [lines 9-19](https://github.com/ctd1500/videojs-hotkeys/blob/master/videojs.hotkeys.js#L9-L19).
Video.js has to be imported in some form.

**Comment by frontHu** [comment]
> I can't offer much help with using this as a node import, but the important code would be [lines 9-19](https://github.com/ctd1500/videojs-hotkeys/blob/master/videojs.hotkeys.js#L9-L19).
> Video.js has to be imported in some form.
