### ISSUE TITLE
0.2.25 does not work for player versions such as 6.13.0, 7.3.0, 7.5.0

### ISSUE THREAD

**Issue by surikat1978** [ctd1500/videojs-hotkeys#64]
Hello! Release 0.2.25 does not work for player versions such as 6.13.0, 7.3.0, 7.5.0
Only in the browser firefox works. What could be the reason ? The script is connected and everything is written without changes. On the version of the player 5.20.5 works fine! Thanks in advance!

$(document).ready(function() {
	videojs('player1').ready(function() {
            this.hotkeys({
			volumeStep: 0.1,
			seekStep: 5,
			enableMute: true,
			enableVolumeScroll: true,
			enableFullscreen: true,
			enableNumbers: true,
			
		});  
	});

});

**Comment by ctd1500** [comment]
I've tested in multiple browsers across OS's and video.js versions and it's worked fine for me.
I even just tried with those listed versions of video.js.
The only thing that changed in this version is a [simple version check](https://github.com/ctd1500/videojs-hotkeys/commit/b174394044e5bcbb913d6dd999057d744e1ff604) to fix a fullscreen bug.

Are there any errors in your browser console or anything?

**Comment by surikat1978** [comment]
If I knew where to look for these errors? I tested for two hours and nothing .. I had to roll back to the old version 5.20.5

**Comment by ctd1500** [comment]
https://kb.mailster.co/how-can-i-open-the-browsers-console/

**Comment by surikat1978** [comment]
@ctd1500 
I know how to open the console! Which tab to look for an error? Where and what should be copied to transfer here?

**Comment by ctd1500** [comment]
The Console tab would have any errors if they exist.
Any possible errors/warnings that say they are from "videojs.hotkeys.js" or "videojs.hotkeys.min.js" on the right side of the console.

**Comment by surikat1978** [comment]
1055-maze-runner-the-death-cure-beguschiy-v-labirinte-lekarstvo-ot-smerti-2018.html:256 Uncaught ReferenceError: VK is not defined
    at 1055-maze-runner-the-death-cure-beguschiy-v-labirinte-lekarstvo-ot-smerti-2018.html:256
video.min.js:12 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2sub' is not a valid selector.
    at http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:4049
    at Function.da.getPlayer (http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:205098)
    at da (http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:203541)
    at http://site.ru/action/1055-maze-runner-the-death-cure-beguschiy-v-labirinte-lekarstvo-ot-smerti-2018.html:573:1
video.min.js:12 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2sub' is not a valid selector.
    at http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:4049
    at Function.da.getPlayer (http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:205098)
    at da (http://site.ru/engine/editor/scripts/common/2sub/video.min.js:12:203541)
    at HTMLDocument.<anonymous> (http://site.ru/templates/megatube/js/libs.js:105:14)
    at i (http://site.ru/engine/classes/js/jquery.js?v=23:2:27151)
    at Object.fireWith [as resolveWith] (http://site.ru/engine/classes/js/jquery.js?v=23:2:27914)
    at Function.ready (http://site.ru/engine/classes/js/jquery.js?v=23:2:29707)
    at HTMLDocument.J (http://site.ru/engine/classes/js/jquery.js?v=23:2:29892)

**Comment by surikat1978** [comment]
There are no special errors for the file. 
Into  js/libs.js   in templates  is it  :   

$(document).ready(function() {
videojs('player1').ready(function() {
this.hotkeys({
volumeStep: 0.1,
seekStep: 5,
enableMute: true,
enableVolumeScroll: true,
enableFullscreen: true,
enableNumbers: true,

```
	});  
});
```

})

**Comment by ctd1500** [comment]
That seems to be a DOM issue where video.js can't find a '#2sub' element in your page.

**Comment by surikat1978** [comment]
Why on version 5 finds? It can not be!

**Comment by ctd1500** [comment]
I don't know what to tell you, it says it right there:
`video.min.js:12 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2sub' is not a valid selector.`

**Comment by surikat1978** [comment]
573 line  it  is   `<script src="{THEME}/js/libs.js"></script>`  included to main.tpl of templates.
And it is written there without any changes.
```
$(document).ready(function() {
videojs('2sub').ready(function() {
```

And etc...  I do not understand what could be the problem for the new version of the player ..?
 I'm  Very Sorry!
