### ISSUE TITLE
alwaysCaptureHotkeys bug

### ISSUE THREAD

**Issue by mirkorobocop** [ctd1500/videojs-hotkeys#65]
Hi, 

I tested many versions of videojs and noticed that the alwaysCaptureHotkeys: true option does not work with any version of videojs above 7.5.4
can anyone confirm this?
I think this commit may be related to this
https://github.com/videojs/video.js/commit/79eadac2523094bdbc61a782d4ad10b72176cbcd

**Comment by ctd1500** [comment]
It still seems to work for some things, like capturing when the seekbar/volume bar is focused.
It appears they got a little aggressive in suppressing all keys presses if any buttons are focused on the control bar.
`alwaysCaptureHotkeys` was always a bit of a hack that broke accessibility in some cases.

I do feel it's a bit much to block `m`, `f`, and other keys when buttons are focused, but I doubt that will change.
@gkatsev
