### ISSUE TITLE
this.hotkeys is not a function

### ISSUE THREAD

**Issue by TongBig** [ctd1500/videojs-hotkeys#67]
this.hotkeys is not a function ---why?

**Comment by ctd1500** [comment]
I would need to see how you are trying to use it in your code to know.

**Comment by TongBig** [comment]
<script src="./static/js/videojs.hotkeys.js"></script>

 videojs('xxxx').ready(function() {
  this.hotkeys({
    volumeStep: 0.1,
    seekStep: 5,
    enableModifiersForNumbers: false
  });
});

**Comment by ctd1500** [comment]
It should certainly be working then, unless `videojs.hotkeys.js` is not getting loaded into the page for some reason.

**Comment by treardon17** [comment]
Currently having the same problem.

**Comment by ctd1500** [comment]
You would need to verify that the script is actually being loaded into the page (with browser dev tools, network or debug tab).

I can't really see another way it wouldn't be working, unless you show me a page where it's broken, or replicate it on jsfiddle.

**Comment by TongBig** [comment]
![hotkey](https://user-images.githubusercontent.com/22976083/72786211-fd77b400-3c67-11ea-8151-d6c5cd337c0c.png)

脚本加载了！！！

**Comment by treardon17** [comment]
I'm importing the script directly instead of loading it through the cdn -- webpack should be bundling it with the rest of my packages.

**Comment by glazec** [comment]
I have the same problem.
``` html
    <script src="https://cdn.sc.gl/videojs-hotkeys/latest/videojs.hotkeys.min.js"></script>

    <script>
      videojs("my-video").ready(function () {
        this.hotkeys({
          volumeStep: 0.1,
          seekStep: 5,
          enableModifiersForNumbers: false,
        });
      });
    </script>
```
![image](https://user-images.githubusercontent.com/22890026/85956970-336b4380-b93e-11ea-8603-656c39b80095.png)

**Comment by ctd1500** [comment]
I cannot reproduce this issue. 
You will need to show me a live site where it's happening, or a jsfiddle/codesandbox where it happens.

**Comment by chengfengliu** [comment]
because they just copy the demo html without changing the script src.

**Comment by chengfengliu** [comment]
Currently having the same problem.And the file had been loaded.

**Comment by chengfengliu** [comment]
> Currently having the same problem.And the file had been loaded.

I fixed it by window.videojs = videojs

**Comment by Ami-OS** [comment]
I have the same problem

https://jsfiddle.net/Kagaku_Accelerator/fz6m9xbw/1/

**Comment by ctd1500** [comment]
> I have the same problem
> 
> https://jsfiddle.net/Kagaku_Accelerator/fz6m9xbw/1/

Line 34 there:
```js
    <script type="text/javascript" src="https//cdn.sc.gl/videojs-hotkeys/0.2/videojs.hotkeys.min.js"></script>
```
missing the `:` after the `https`

**Comment by Ami-OS** [comment]
@ctd1500 oh, thx

**Comment by JunkMeal** [comment]
I have the same problem. And isn't it because I am using a newer version of videojs?

**Comment by JunkMeal** [comment]
> I have the same problem. And isn't it because I am using a newer version of videojs?
aaaa I just tried to downgrade, and it still doesn't work

**Comment by JunkMeal** [comment]
Just fixed it 👍
