### ISSUE TITLE
use videojs-hotkeys in Angular 

### ISSUE THREAD

**Issue by akashgaikwad91** [ctd1500/videojs-hotkeys#70]
Thank you Team for the plugin.
Guys, can anyone here give an example of how to make use of videojs-hotkeys in Angular.

**Comment by johnpankowicz** [comment]
@akashgaikwad91 Did you come up with an example? If so, will you please share it here?

**Comment by johnpankowicz** [comment]
I just found a solution myself. I followed the sample that thijstriemstra gave a link to in issue [#6747](https://github.com
