### ISSUE TITLE
Uncaught error when pressing fullscreen shortcut with captureDocumentHotkeys set to true and video player focused

### ISSUE THREAD

**Issue by Coteh** [ctd1500/videojs-hotkeys#74]
Hi, I recently installed v0.2.27 of videojs-hotkeys via npm and I also have v7.7.5 of videojs installed via npm as well (and updated it to 7.11.0 as I was writing this issue). Our team is using video.js as a streaming player in a React project and we are looking to add hotkey support for fullscreen. I stumbled upon this project, which has that and a bunch of other stuff like volume slider and mute hotkey OOTB, all of which would be great to have in our app. One problem I seem to be running into though is an issue where if I enable `captureDocumentHotkeys` and then press F in Firefox while focusing on the video player, it will throw an `Uncaught (in promise) undefined` exception, with the following stacktrace:

```
errorHandler video.es.js:23691
errorHandler self-hosted:1161
func video.es.js:2084
dispatcher video.es.js:1898
(Async: EventListener.handleEvent)
on video.es.js:1918
one video.es.js:2089
listen video.es.js:2666
one video.es.js:2780
requestFullscreen video.es.js:23695
requestFullscreen video.es.js:23678
q videojs.hotkeys.min.js:2
q self-hosted:1161
dispatcher video.es.js:1898
(Async: EventListener.handleEvent)
on video.es.js:1918
listen video.es.js:2666
on video.es.js:2716
Player video.es.js:21373
videojs$1 video.es.js:26730
Streaming Streaming.tsx:261 (this is the line where videojs is initialized)
```

I threw in a console.log inside the `documentHotkeysFocusElementFilter` callback I passed into hotkeys options and I notice that two logs are printed when I press F while focused on video player, but when I'm not focused on the element, only one log is printed.

Also, in Chrome, I get the following message alongside the error: `Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`

The following is how I initialized the hotkeys plugin if that helps:

```
player.ready(function() {
    this.hotkeys({
        enableNumbers: false,
        captureDocumentHotkeys: true,
        documentHotkeysFocusElementFilter: e => e.tagName.toLowerCase() === "body",
        rewindKey: () => false,
        forwardKey: () => false,
        playPauseKey: () => false,
    });
});
```

Let me know if there's anything here that I need to change, thanks.

(also, as a sidenote, mute hotkey does not work for me in Chrome)

**Comment by ctd1500** [comment]
I'm still working on some other updates, but I believe [this gist](https://gist.github.com/ctd1500/600259ae462e2f7a69fc0e863b9954fa) will fix those issues if you want to give it a try.
