### ISSUE TITLE
[bug] Spacebar hotkey only works every other time hotkeys() is called

### ISSUE THREAD

**Issue by designosis** [ctd1500/videojs-hotkeys#80]
## Summary of Problem

On a page that triggeres multiple videos, the hotkeys work perfectly on the first video. However spacebar only works EVERY OTHER TIME. How do you force the SPACE hotkey to work reliably?

## Steps to reproduce

1. Open https://jsfiddle.net/o82kw4jg/1/ in Chrome OSX (untested in Windows)
2. Click one of the 1-5 buttons to trigger a video.
3. It works great ... you can hit SPACEBAR, arrows to skip, and numbers to jump.
4. Now click any of the 1-5 buttons (same or different) to trigger another video.
5. Arrows work, numbers work, but SPACEBAR does not.
6. Click a 1-5 button
7. SPACEBAR works again.

## Expected behaviour

Spacebar always plays/pauses the video, regardless of focus.

## Actual behaviour

Spacebar only works every other time.

**Comment by neokio** [comment]
Bump ... does no-one else experience this??

**Comment by TomRaz** [comment]
I'm experiencing the same issue
